version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - custom-network
  redis:
    image: "redis:alpine"
    networks:
      - custom-network
    
networks:
  custom-network:
    external:
      name: custom-network

